services:
    _defaults:
        autowire: true
        autoconfigure: true

    BohnMedia\ContaoFlagIconsBundle\:
        resource: '../src/'
        exclude:
            - '../src/BohnMediaContaoFlagIconsBundle.php'
            - '../src/ContaoManager/'
